version: '3'
services:
    php:
        container_name: datak_php
        build:
            context: ./Docker/config/php
            dockerfile: dev.Dockerfile
        volumes:
            - ./api:/usr/share/nginx
            - ./Docker/config/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            datak-network:

    nginx:
        container_name: datak_nginx
        image: nginx:latest
        ports:
            - 8000:80
        volumes:
            - ./api:/usr/share/nginx
            - ./Docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            datak-network:

    elasticsearch:
        image: elasticsearch:8.0.1
        container_name: datak_elasticsearch
        volumes:
            - elastic_data:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        environment:
            - "discovery.type=single-node"
            - ELASTIC_PASSWORD=123456
        networks:
            datak-network:

#    kibana:
#         depends_on:
#             - elasticsearch
#         image: kibana:8.0.1
#         container_name: datak_kibana
#         volumes:
#             - certs:/usr/share/kibana/config/certs
#             - kibanadata:/usr/share/kibana/data
#         ports:
#             - 5601:5601
#         environment:
#             - SERVERNAME=kibana
#             - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#             - ELASTICSEARCH_USERNAME=elastic
#             - ELASTICSEARCH_PASSWORD=123456
#         networks:
#             datak-network:

networks:
    datak-network:

volumes:
    elastic_data:
    certs:
    kibanadata:




